Repository jbwheatley/pact4s, pull requests merged in 2024-03, with the labels that each got.

#527 Replace deprecated URL constructor with URI.toURL in main
  models/src/main/scala/pact4s/provider/ProviderInfoBuilder.scala
Labels: bug

#521 🐛 fix(provider-verification): allow empty tags when using pending pacts
  models/src/main/scala/pact4s/provider/PactSource.scala
  models/src/main/scala/pact4s/provider/ProviderInfoBuilder.scala
  models/src/test/scala/pact4s/provider/PactBrokerWithSelectorsSpec.scala
  shared/src/test/scala/pact4s/MockProviderServer.scala
Labels: bug

#555 🐛 fix(provider-verification): allow empty tags when using pending pacts (Java 8)
  models/src/main/scala/pact4s/provider/PactSource.scala
  models/src/main/scala/pact4s/provider/ProviderInfoBuilder.scala
  models/src/test/scala/pact4s/provider/PactBrokerWithSelectorsSpec.scala
  shared/src/test/scala/pact4s/MockProviderServer.scala
Labels: bug

#529 Add zio-test support in main
  README.md
  build.sbt
  project/Dependencies.scala
  ziotest-pact/src/main/scala/pact4s/ziotest/MessagePactForger.scala
  ziotest-pact/src/main/scala/pact4s/ziotest/PactVerifier.scala
  ziotest-pact/src/main/scala/pact4s/ziotest/RequestResponsePactForger.scala
  ziotest-pact/src/test/resources/logback-test.xml
  ziotest-pact/src/test/scala/pact4s/ziotest/message/PactForgerSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/message/PactVerifierBrokerSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/message/PactVerifierFileSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactForgerSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactVerifierBrokerFeatureBranchSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactVerifierBrokerMatchingBranchSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactVerifierBrokerSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactVerifierStateChangeFunctionSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactVerifierSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PendingPactVerificationSuite.scala
Labels: enhancement

#532 Add zio-test support in java8
  README.md
  build.sbt
  project/Dependencies.scala
  ziotest-pact/src/main/scala/pact4s/ziotest/MessagePactForger.scala
  ziotest-pact/src/main/scala/pact4s/ziotest/PactVerifier.scala
  ziotest-pact/src/main/scala/pact4s/ziotest/RequestResponsePactForger.scala
  ziotest-pact/src/test/resources/logback-test.xml
  ziotest-pact/src/test/scala/pact4s/ziotest/message/PactForgerSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/message/PactVerifierBrokerSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/message/PactVerifierFileSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactForgerSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactVerifierBrokerFeatureBranchSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactVerifierBrokerMatchingBranchSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactVerifierBrokerSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactVerifierStateChangeFunctionSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PactVerifierSuite.scala
  ziotest-pact/src/test/scala/pact4s/ziotest/requestresponse/PendingPactVerificationSuite.scala
Labels: enhancement

#599 📦 ci: upgrade Actions versions
  .github/workflows/pr-build.yml
  .github/workflows/release.yml
  .github/workflows/renovatebot.yml
Labels: ci
